### ISSUE TITLE
Commenting is broken.

### ISSUE THREAD

**Issue by MHordecki** [mina86/mina86.com#2]
When clicking the "Add comment" button, I get a bunch of JS exceptions.

Console log:

```
talkyard-comments.min.js:10 Talkyard comments: Starting... (disable logging by setting talkyardLogLevel = 'warn')
talkyard-comments.min.js:10 Talkyard comments: loadCommentsCreateEditor()
talkyard-comments.min.js:10 Talkyard comments: found commentsElem
talkyard-comments.min.js:10 Talkyard comments: inserted commentsIframe
talkyard-comments.min.js:10 Talkyard comments: inserted editorWrapper
talkyard-comments.min.js:10 Talkyard comments: inserted editorIframe
talkyard-comments.min.js:10 Talkyard comments: got 'iframeInited' message
talkyard-comments.min.js:10 Talkyard comments: got 'iframeInited' message
talkyard-comments.min.js:10 Talkyard comments: it's the comments iframe
slim-bundle.min.js:10 Error registering service worker [TyESWREGKO] DOMException: Failed to register a ServiceWorker for scope ('https://comments-for-mina86-com.talkyard.net/') with script ('https://comments-for-mina86-com.talkyard.net/talkyard-service-worker.min.js'): The user denied permission to use Service Worker.
(anonymous) @ slim-bundle.min.js:10
slim-bundle.min.js:10 Error subscribing to events via service worker [TyE5RM57] DOMException: Failed to register a ServiceWorker for scope ('https://comments-for-mina86-com.talkyard.net/') with script ('https://comments-for-mina86-com.talkyard.net/talkyard-service-worker.min.js'): The user denied permission to use Service Worker.
(anonymous) @ slim-bundle.min.js:10
slim-bundle.min.js:10 Error sending start-magic-time to service worker [TyESWMGCTM] DOMException: Failed to register a ServiceWorker for scope ('https://comments-for-mina86-com.talkyard.net/') with script ('https://comments-for-mina86-com.talkyard.net/talkyard-service-worker.min.js'): The user denied permission to use Service Worker.
(anonymous) @ slim-bundle.min.js:10
talkyard-comments.min.js:10 Uncaught DOMException: Failed to execute 'postMessage' on 'Window': Invalid target origin '//comments-for-mina86-com.talkyard.net' in a call to 'postMessage'.
    at i (https://c1.ty-cdn.net/-/talkyard-comments.min.js:10:4463)
    at r (https://c1.ty-cdn.net/-/talkyard-comments.min.js:10:4288)
    at n (https://c1.ty-cdn.net/-/talkyard-comments.min.js:10:4156)
talkyard-comments.min.js:10 Uncaught DOMException: Failed to execute 'postMessage' on 'Window': Invalid target origin '//comments-for-mina86-com.talkyard.net' in a call to 'postMessage'.
    at i (https://c1.ty-cdn.net/-/talkyard-comments.min.js:10:4463)
    at r (https://c1.ty-cdn.net/-/talkyard-comments.min.js:10:4288)
    at n (https://c1.ty-cdn.net/-/talkyard-comments.min.js:10:4156)
talkyard-comments.min.js:10 Uncaught DOMException: Failed to execute 'postMessage' on 'Window': Invalid target origin '//comments-for-mina86-com.talkyard.net' in a call to 'postMessage'.
    at i (https://c1.ty-cdn.net/-/talkyard-comments.min.js:10:4463)
    at r (https://c1.ty-cdn.net/-/talkyard-comments.min.js:10:4288)
    at n (https://c1.ty-cdn.net/-/talkyard-comments.min.js:10:4156)
talkyard-comments.min.js:10 Uncaught DOMException: Failed to execute 'postMessage' on 'Window': Invalid target origin '//comments-for-mina86-com.talkyard.net' in a call to 'postMessage'.
    at i (https://c1.ty-cdn.net/-/talkyard-comments.min.js:10:4463)
    at r (https://c1.ty-cdn.net/-/talkyard-comments.min.js:10:4288)
    at n (https://c1.ty-cdn.net/-/talkyard-comments.min.js:10:4156)
```

**Comment by mina86** [comment]
FIxed. Thanks.
